SRC = src/

beoc: $(SRC)basic-example-of-creating-thread.c
	gcc $(SRC)basic-example-of-creating-thread.c -o beoc -lpthread

a: $(SRC)a-struct-reader-thread.c
	gcc $(SRC)a-struct-reader-thread.c -o asrt -lpthread